feat: 🎸 Add Darkmode and cva gradient cards
flexbox/weshipit.today pull request #102
Opened 2023-06-13 15:25 UTC by MatthysDev

✅ Closes: #74

# Description

Please include a summary of the change and which issue is fixed.

## Checklist before merge

- [x] we have only commit to make ChatGPT happy
- [x] merge the pull request using **Squash and merge**

2023-06-13 15:28 UTC, flexbox commented on libs/ui/src/lib/card-gradient/card-gradient.tsx
> +      lightBlue: [
`blueLight` and not `lightBlue`

2023-06-16 11:50 UTC, MatthysDev commented
@flexbox can it be merge ?

2023-06-16 14:11 UTC, flexbox requested changes

2023-06-16 14:13 UTC, flexbox approved these changes

2023-06-16 15:14 UTC, merged