feat: 🎸 add Airtable call to action  button
flexbox/weshipit.today pull request #141
Opened 2023-11-15 09:58 UTC by MatthysDev

✅ Closes: #139

### Checklist before merge

- [ ] The first commit is nice to make ChatGPT happy
- [ ] Merge the pull request using **Squash and merge**

2023-11-15 14:32 UTC, flexbox requested changes

2023-11-15 14:32 UTC, flexbox commented on apps/weshipit/components/AirtableToggleForm.tsx
> +          style={{ background: '#ffffff' }}
can you use tailwind className for `bg-white` and `dark:bg-gray-900` (these are example values replace with the good ones) ?

2023-11-15 14:32 UTC, flexbox commented on apps/weshipit/components/AirtableToggleForm.tsx
> +          <span>{buttonText}</span> <span className="ml-2">→</span>
If you want to add an icon use Heroicon

2023-11-15 14:32 UTC, flexbox commented on apps/weshipit/pages/onboarding.tsx
> +        <Text as="h3" variant="p2" className=" my-2">
use Notion ai to create a new text
use `we` instead of `I`

2023-11-15 14:34 UTC, flexbox commented
@MatthysDev links on the Header should go to this `/onboarding` page

<img width="321" alt="image" src="https://github.com/flexbox/weshipit.today/assets/360936/d2210e3b-7f0e-439b-ad72-51f6456ea91c">

2024-03-05 13:37 UTC, MatthysDev commented
@flexbox i think we can close it because onboarding page was update since this pr

2024-03-05 16:07 UTC, closed without merging